"""
Definitions.
"""

from enum import Enum

from pydantic import BaseModel


class SystemEvent(Enum):
    NONE = 'NONE'
    ELAPSED_TIME = 'ELAPSED_TIME'
    DEADLINE_MISSES = 'DEADLINE_MISSES'
    CPU_EXECUTION_TIME = 'CPU_EXECUTION_TIME'
    THREAD_EXECUTION_TIME = 'THREAD_EXECUTION_TIME'
    RUNNING_THREAD = 'RUNNING_THREAD'
    JOB_UTILIZATION = 'JOB_UTILIZATION'
    JOB_UTILIZATION_PER_PERIOD = 'JOB_UTILIZATION_PER_PERIOD'
    CPU_CLOCK = 'CPU_CLOCK'
    CPU_VOLTAGE = 'CPU_VOLTAGE'
    PREDICTED_JOB_UTILIZATION = 'PREDICTED_JOB_UTILIZATION'
    CORE = 'CORE'


class PMUEvent(Enum):
    # Fixed counters
    CPU_CYCLES = 'CPU_CYCLES'
    INSTRUCTIONS_RETIRED = 'INSTRUCTIONS_RETIRED'

    # Programmable counters (2 simultaneous channels)
    EXCEPTIONS_TAKEN = 'EXCEPTIONS_TAKEN'
    INTEGER_LOAD_INSTRUCTIONS_RETIRED = 'INTEGER_LOAD_INSTRUCTIONS_RETIRED'

    INTEGER_STORE_INSTRUCTIONS_RETIRED = 'INTEGER_STORE_INSTRUCTIONS_RETIRED'
    ATOMIC_MEMORY_INSTRUCTIONS_RETIRED = 'ATOMIC_MEMORY_INSTRUCTIONS_RETIRED'

    SYSTEM_INSTRUCTIONS_RETIRED = 'SYSTEM_INSTRUCTIONS_RETIRED'
    INTEGER_ARITHMETIC_INSTRUCTIONS_RETIRED = 'INTEGER_ARITHMETIC_INSTRUCTIONS_RETIRED'

    CONDITIONAL_BRANCHES_RETIRED = 'CONDITIONAL_BRANCHES_RETIRED'
    JAL_INSTRUCTIONS_RETIRED = 'JAL_INSTRUCTIONS_RETIRED'

    JALR_INSTRUCTIONS_RETIRED = 'JALR_INSTRUCTIONS_RETIRED'
    INTEGER_MULTIPLICATION_INSTRUCTIONS_RETIRED = 'INTEGER_MULTIPLICATION_INSTRUCTIONS_RETIRED'

    INTEGER_DIVISION_INSTRUCTIONS_RETIRED = 'INTEGER_DIVISION_INSTRUCTIONS_RETIRED'
    FLOATING_POINT_LOAD_INSTRUCTION_RETIRED = 'FLOATING_POINT_LOAD_INSTRUCTION_RETIRED'

    FLOATING_POINT_STORE_INSTRUCTION_RETIRED = 'FLOATING_POINT_STORE_INSTRUCTION_RETIRED'
    FLOATING_POINT_ADDITION_RETIRED = 'FLOATING_POINT_ADDITION_RETIRED'

    FLOATING_POINT_MULTIPLICATION_RETIRED = 'FLOATING_POINT_MULTIPLICATION_RETIRED'
    FLOATING_POINT_FUSED_MULTIPLY_ADD_RETIRED = 'FLOATING_POINT_FUSED_MULTIPLY_ADD_RETIRED'

    FLOATING_POINT_DIVISION_OR_SQUARE_ROOT_RETIRED = 'FLOATING_POINT_DIVISION_OR_SQUARE_ROOT_RETIRED'
    OTHER_FLOATING_POINT_INSTRUCTION_RETIRED = 'OTHER_FLOATING_POINT_INSTRUCTION_RETIRED'

    ADDRESS_GENERATION_INTERLOCK = 'ADDRESS_GENERATION_INTERLOCK'
    LONG_LATENCY_INTERLOCK = 'LONG_LATENCY_INTERLOCK'

    CSR_READ_INTERLOCK = 'CSR_READ_INTERLOCK'
    INSTRUCTION_CACHE_ITIM_BUSY = 'INSTRUCTION_CACHE_ITIM_BUSY'

    DATA_CACHE_DTIM_BUSY = 'DATA_CACHE_DTIM_BUSY'
    BRANCH_DIRECTION_MISPREDICTION = 'BRANCH_DIRECTION_MISPREDICTION'

    BRANCH_JUMP_TARGET_MISPREDICTION = 'BRANCH_JUMP_TARGET_MISPREDICTION'
    PIPELINE_FLUSH_FROM_CSR_WRITE = 'PIPELINE_FLUSH_FROM_CSR_WRITE'

    PIPELINE_FLUSH_FROM_OTHER_EVENT = 'PIPELINE_FLUSH_FROM_OTHER_EVENT'
    INTEGER_MULTIPLICATION_INTERLOCK = 'INTEGER_MULTIPLICATION_INTERLOCK'

    FLOATING_POINT_INTERLOCK = 'FLOATING_POINT_INTERLOCK'
    INSTRUCTION_CACHE_MISS = 'INSTRUCTION_CACHE_MISS'

    DATA_CACHE_MISS_OR_MEMORY_MAPPED_IO_ACCESS = 'DATA_CACHE_MISS_OR_MEMORY_MAPPED_IO_ACCESS'
    DATA_CACHE_WRITE_BACK = 'DATA_CACHE_WRITE_BACK'

    INSTRUCTION_TLB_MISS = 'INSTRUCTION_TLB_MISS'
    DATA_TLB_MISS = 'DATA_TLB_MISS'

    L2_TLB_MISS = 'L2_TLB_MISS'
    L1_CACHE_MISS = 'L1_CACHE_MISS'


class L2CachePMUEvent(Enum):
    # L2 Programmable counters (6 simultaneous channels)
    L2_INNER_PUTFULLDATA = 'L2_INNER_PUTFULLDATA'
    L2_INNER_PUTPARTIALDATA = 'L2_INNER_PUTPARTIALDATA'
    L2_INNER_ATOMICDATA = 'L2_INNER_ATOMICDATA'
    L2_INNER_GET = 'L2_INNER_GET'
    L2_INNER_PREFETCH_READ = 'L2_INNER_PREFETCH_READ'
    L2_INNER_PREFETCH_WRITE = 'L2_INNER_PREFETCH_WRITE'

    L2_INNER_ACQUIREBLOCK_NTOB = 'L2_INNER_ACQUIREBLOCK_NTOB'
    L2_INNER_ACQUIREBLOCK_NTOT = 'L2_INNER_ACQUIREBLOCK_NTOT'
    L2_INNER_ACQUIREBLOCK_BTOT = 'L2_INNER_ACQUIREBLOCK_BTOT'
    L2_INNER_ACQUIREPERM_NTOT = 'L2_INNER_ACQUIREPERM_NTOT'
    L2_INNER_ACQUIREPERM_BTOT = 'L2_INNER_ACQUIREPERM_BTOT'
    L2_INNER_RELEASE_TOB = 'L2_INNER_RELEASE_TOB'

    L2_INNER_RELEASE_TTON = 'L2_INNER_RELEASE_TTON'
    L2_INNER_RELEASE_BTON = 'L2_INNER_RELEASE_BTON'
    L2_INNER_RELEASEDATA_TOB = 'L2_INNER_RELEASEDATA_TOB'
    L2_INNER_RELEASEDATA_TTON = 'L2_INNER_RELEASEDATA_TTON'
    L2_INNER_RELEASEDATA_BTON = 'L2_INNER_RELEASEDATA_BTON'
    L2_OUTER_PROBEBLOCK_TOT = 'L2_OUTER_PROBEBLOCK_TOT'

    L2_OUTER_PROBEBLOCK_TOB = 'L2_OUTER_PROBEBLOCK_TOB'
    L2_OUTER_PROBEBLOCK_TON = 'L2_OUTER_PROBEBLOCK_TON'
    L2_INNER_PUTFULLDATA_HIT_L2 = 'L2_INNER_PUTFULLDATA_HIT_L2'
    L2_INNER_PUTPARTIALDATA_HIT_L2 = 'L2_INNER_PUTPARTIALDATA_HIT_L2'
    L2_INNER_ATOMICDATA_HIT_L2 = 'L2_INNER_ATOMICDATA_HIT_L2'
    L2_INNER_GET_HIT_L2 = 'L2_INNER_GET_HIT_L2'

    L2_INNER_PREFETCH_HIT_L2 = 'L2_INNER_PREFETCH_HIT_L2'
    L2_INNER_ACQUIREBLOCK_HIT_L2 = 'L2_INNER_ACQUIREBLOCK_HIT_L2'
    L2_INNER_ACQUIREPERM_HIT_L2 = 'L2_INNER_ACQUIREPERM_HIT_L2'
    L2_INNER_RELEASE_HIT_L2 = 'L2_INNER_RELEASE_HIT_L2'
    L2_INNER_RELEASEDATA_HIT_L2 = 'L2_INNER_RELEASEDATA_HIT_L2'
    L2_OUTER_PROBE_HIT_L2 = 'L2_OUTER_PROBE_HIT_L2'

    L2_INNER_PUTFULLDATA_HIT_L2_SHARED = 'L2_INNER_PUTFULLDATA_HIT_L2_SHARED'
    L2_INNER_PUTPARTIALDATA_HIT_L2_SHARED = 'L2_INNER_PUTPARTIALDATA_HIT_L2_SHARED'
    L2_INNER_ATOMICDATA_HIT_L2_SHARED = 'L2_INNER_ATOMICDATA_HIT_L2_SHARED'
    L2_INNER_GET_HIT_L2_SHARED = 'L2_INNER_GET_HIT_L2_SHARED'
    L2_INNER_PREFETCH_HIT_L2_SHARED = 'L2_INNER_PREFETCH_HIT_L2_SHARED'
    L2_INNER_ACQUIREBLOCK_HIT_L2_SHARED = 'L2_INNER_ACQUIREBLOCK_HIT_L2_SHARED'

    L2_INNER_ACQUIREPERM_HIT_L2_SHARED = 'L2_INNER_ACQUIREPERM_HIT_L2_SHARED'
    L2_OUTER_PROBE_HIT_L2_SHARED = 'L2_OUTER_PROBE_HIT_L2_SHARED'
    L2_OUTER_PROBE_HIT_L2_MODIFIED = 'L2_OUTER_PROBE_HIT_L2_MODIFIED'
    L2_OUTER_ACQUIREBLOCK_NTOB_L2_MISS = 'L2_OUTER_ACQUIREBLOCK_NTOB_L2_MISS'
    L2_OUTER_ACQUIREBLOCK_NTOT_L2_MISS = 'L2_OUTER_ACQUIREBLOCK_NTOT_L2_MISS'
    L2_OUTER_ACQUIREBLOCK_BTOT_L2_MISS = 'L2_OUTER_ACQUIREBLOCK_BTOT_L2_MISS'

    L2_OUTER_ACQUIREPERM_NTOT_L2_MISS = 'L2_OUTER_ACQUIREPERM_NTOT_L2_MISS'
    L2_OUTER_ACQUIREPERM_BTOT_L2_MISS = 'L2_OUTER_ACQUIREPERM_BTOT_L2_MISS'
    L2_OUTER_RELEASE_TOB_EVICTION = 'L2_OUTER_RELEASE_TOB_EVICTION'
    L2_OUTER_RELEASE_TON_EVICTION = 'L2_OUTER_RELEASE_TON_EVICTION'
    L2_OUTER_RELEASE_BTON_EVICTION = 'L2_OUTER_RELEASE_BTON_EVICTION'
    L2_OUTER_RELEASEDATA_TOB = 'L2_OUTER_RELEASEDATA_TOB'

    L2_OUTER_RELEASEDATA_TTON_DIRTY_EVICTION = 'L2_OUTER_RELEASEDATA_TTON_DIRTY_EVICTION'
    L2_OUTER_RELEASEDATA_BTON = 'L2_OUTER_RELEASEDATA_BTON'
    L2_INNER_PROBEBLOCK_TOT_CODE_MISS = 'L2_INNER_PROBEBLOCK_TOT_CODE_MISS'
    L2_INNER_PROBEBLOCK_TOB_LOAD_MISS = 'L2_INNER_PROBEBLOCK_TOB_LOAD_MISS'
    L2_INNER_PROBEBLOCK_TON_STORE_MISS = 'L2_INNER_PROBEBLOCK_TON_STORE_MISS'
    L2_DEMAND_MISS_HIT_MSHR_ALLOC_HINT = 'L2_DEMAND_MISS_HIT_MSHR_ALLOC_HINT'
    L2_CACHE_MISS = 'L2_CACHE_MISS'
    L1_BY_L2 = 'L1_BY_L2'


class PMUEventVariance(Enum):
    # Fixed counters
    CPU_CYCLES_VARIANCE = 'CPU_CYCLES_VARIANCE'
    INSTRUCTIONS_RETIRED_VARIANCE = 'INSTRUCTIONS_RETIRED_VARIANCE'

    # Programmable counters (2 simultaneous channels)
    EXCEPTIONS_TAKEN_VARIANCE = 'EXCEPTIONS_TAKEN_VARIANCE'
    INTEGER_LOAD_INSTRUCTIONS_RETIRED_VARIANCE = 'INTEGER_LOAD_INSTRUCTIONS_RETIRED_VARIANCE'

    INTEGER_STORE_INSTRUCTIONS_RETIRED_VARIANCE = 'INTEGER_STORE_INSTRUCTIONS_RETIRED_VARIANCE'
    ATOMIC_MEMORY_INSTRUCTIONS_RETIRED_VARIANCE = 'ATOMIC_MEMORY_INSTRUCTIONS_RETIRED_VARIANCE'

    SYSTEM_INSTRUCTIONS_RETIRED_VARIANCE = 'SYSTEM_INSTRUCTIONS_RETIRED_VARIANCE'
    INTEGER_ARITHMETIC_INSTRUCTIONS_RETIRED_VARIANCE = 'INTEGER_ARITHMETIC_INSTRUCTIONS_RETIRED_VARIANCE'

    CONDITIONAL_BRANCHES_RETIRED_VARIANCE = 'CONDITIONAL_BRANCHES_RETIRED_VARIANCE'
    JAL_INSTRUCTIONS_RETIRED_VARIANCE = 'JAL_INSTRUCTIONS_RETIRED_VARIANCE'

    JALR_INSTRUCTIONS_RETIRED_VARIANCE = 'JALR_INSTRUCTIONS_RETIRED_VARIANCE'
    INTEGER_MULTIPLICATION_INSTRUCTIONS_RETIRED_VARIANCE = 'INTEGER_MULTIPLICATION_INSTRUCTIONS_RETIRED_VARIANCE'

    INTEGER_DIVISION_INSTRUCTIONS_RETIRED_VARIANCE = 'INTEGER_DIVISION_INSTRUCTIONS_RETIRED_VARIANCE'
    FLOATING_POINT_LOAD_INSTRUCTION_RETIRED_VARIANCE = 'FLOATING_POINT_LOAD_INSTRUCTION_RETIRED_VARIANCE'

    FLOATING_POINT_STORE_INSTRUCTION_RETIRED_VARIANCE = 'FLOATING_POINT_STORE_INSTRUCTION_RETIRED_VARIANCE'
    FLOATING_POINT_ADDITION_RETIRED_VARIANCE = 'FLOATING_POINT_ADDITION_RETIRED_VARIANCE'

    FLOATING_POINT_MULTIPLICATION_RETIRED_VARIANCE = 'FLOATING_POINT_MULTIPLICATION_RETIRED_VARIANCE'
    FLOATING_POINT_FUSED_MULTIPLY_ADD_RETIRED_VARIANCE = 'FLOATING_POINT_FUSED_MULTIPLY_ADD_RETIRED_VARIANCE'

    FLOATING_POINT_DIVISION_OR_SQUARE_ROOT_RETIRED_VARIANCE = 'FLOATING_POINT_DIVISION_OR_SQUARE_ROOT_RETIRED_VARIANCE'
    OTHER_FLOATING_POINT_INSTRUCTION_RETIRED_VARIANCE = 'OTHER_FLOATING_POINT_INSTRUCTION_RETIRED_VARIANCE'

    ADDRESS_GENERATION_INTERLOCK_VARIANCE = 'ADDRESS_GENERATION_INTERLOCK_VARIANCE'
    LONG_LATENCY_INTERLOCK_VARIANCE = 'LONG_LATENCY_INTERLOCK_VARIANCE'

    CSR_READ_INTERLOCK_VARIANCE = 'CSR_READ_INTERLOCK_VARIANCE'
    INSTRUCTION_CACHE_ITIM_BUSY_VARIANCE = 'INSTRUCTION_CACHE_ITIM_BUSY_VARIANCE'

    DATA_CACHE_DTIM_BUSY_VARIANCE = 'DATA_CACHE_DTIM_BUSY_VARIANCE'
    BRANCH_DIRECTION_MISPREDICTION_VARIANCE = 'BRANCH_DIRECTION_MISPREDICTION_VARIANCE'

    BRANCH_JUMP_TARGET_MISPREDICTION_VARIANCE = 'BRANCH_JUMP_TARGET_MISPREDICTION_VARIANCE'
    PIPELINE_FLUSH_FROM_CSR_WRITE_VARIANCE = 'PIPELINE_FLUSH_FROM_CSR_WRITE_VARIANCE'

    PIPELINE_FLUSH_FROM_OTHER_EVENT_VARIANCE = 'PIPELINE_FLUSH_FROM_OTHER_EVENT_VARIANCE'
    INTEGER_MULTIPLICATION_INTERLOCK_VARIANCE = 'INTEGER_MULTIPLICATION_INTERLOCK_VARIANCE'

    FLOATING_POINT_INTERLOCK_VARIANCE = 'FLOATING_POINT_INTERLOCK_VARIANCE'
    INSTRUCTION_CACHE_MISS_VARIANCE = 'INSTRUCTION_CACHE_MISS_VARIANCE'

    DATA_CACHE_MISS_OR_MEMORY_MAPPED_IO_ACCESS_VARIANCE = 'DATA_CACHE_MISS_OR_MEMORY_MAPPED_IO_ACCESS_VARIANCE'
    DATA_CACHE_WRITE_BACK_VARIANCE = 'DATA_CACHE_WRITE_BACK_VARIANCE'

    INSTRUCTION_TLB_MISS_VARIANCE = 'INSTRUCTION_TLB_MISS_VARIANCE'
    DATA_TLB_MISS_VARIANCE = 'DATA_TLB_MISS_VARIANCE'

    L2_TLB_MISS_VARIANCE = 'L2_TLB_MISS_VARIANCE'
    L1_CACHE_MISS_VARIANCE = 'L1_CACHE_MISS_VARIANCE'


class L2CachePMUEventVariance(Enum):
    # L2 Programmable counters (6 simultaneous channels)
    L2_INNER_PUTFULLDATA_VARIANCE = 'L2_INNER_PUTFULLDATA_VARIANCE'
    L2_INNER_PUTPARTIALDATA_VARIANCE = 'L2_INNER_PUTPARTIALDATA_VARIANCE'
    L2_INNER_ATOMICDATA_VARIANCE = 'L2_INNER_ATOMICDATA_VARIANCE'
    L2_INNER_GET_VARIANCE = 'L2_INNER_GET_VARIANCE'
    L2_INNER_PREFETCH_READ_VARIANCE = 'L2_INNER_PREFETCH_READ_VARIANCE'
    L2_INNER_PREFETCH_WRITE_VARIANCE = 'L2_INNER_PREFETCH_WRITE_VARIANCE'

    L2_INNER_ACQUIREBLOCK_NTOB_VARIANCE = 'L2_INNER_ACQUIREBLOCK_NTOB_VARIANCE'
    L2_INNER_ACQUIREBLOCK_NTOT_VARIANCE = 'L2_INNER_ACQUIREBLOCK_NTOT_VARIANCE'
    L2_INNER_ACQUIREBLOCK_BTOT_VARIANCE = 'L2_INNER_ACQUIREBLOCK_BTOT_VARIANCE'
    L2_INNER_ACQUIREPERM_NTOT_VARIANCE = 'L2_INNER_ACQUIREPERM_NTOT_VARIANCE'
    L2_INNER_ACQUIREPERM_BTOT_VARIANCE = 'L2_INNER_ACQUIREPERM_BTOT_VARIANCE'
    L2_INNER_RELEASE_TOB_VARIANCE = 'L2_INNER_RELEASE_TOB_VARIANCE'

    L2_INNER_RELEASE_TTON_VARIANCE = 'L2_INNER_RELEASE_TTON_VARIANCE'
    L2_INNER_RELEASE_BTON_VARIANCE = 'L2_INNER_RELEASE_BTON_VARIANCE'
    L2_INNER_RELEASEDATA_TOB_VARIANCE = 'L2_INNER_RELEASEDATA_TOB_VARIANCE'
    L2_INNER_RELEASEDATA_TTON_VARIANCE = 'L2_INNER_RELEASEDATA_TTON_VARIANCE'
    L2_INNER_RELEASEDATA_BTON_VARIANCE = 'L2_INNER_RELEASEDATA_BTON_VARIANCE'
    L2_OUTER_PROBEBLOCK_TOT_VARIANCE = 'L2_OUTER_PROBEBLOCK_TOT_VARIANCE'

    L2_OUTER_PROBEBLOCK_TOB_VARIANCE = 'L2_OUTER_PROBEBLOCK_TOB_VARIANCE'
    L2_OUTER_PROBEBLOCK_TON_VARIANCE = 'L2_OUTER_PROBEBLOCK_TON_VARIANCE'
    L2_INNER_PUTFULLDATA_HIT_L2_VARIANCE = 'L2_INNER_PUTFULLDATA_HIT_L2_VARIANCE'
    L2_INNER_PUTPARTIALDATA_HIT_L2_VARIANCE = 'L2_INNER_PUTPARTIALDATA_HIT_L2_VARIANCE'
    L2_INNER_ATOMICDATA_HIT_L2_VARIANCE = 'L2_INNER_ATOMICDATA_HIT_L2_VARIANCE'
    L2_INNER_GET_HIT_L2_VARIANCE = 'L2_INNER_GET_HIT_L2_VARIANCE'

    L2_INNER_PREFETCH_HIT_L2_VARIANCE = 'L2_INNER_PREFETCH_HIT_L2_VARIANCE'
    L2_INNER_ACQUIREBLOCK_HIT_L2_VARIANCE = 'L2_INNER_ACQUIREBLOCK_HIT_L2_VARIANCE'
    L2_INNER_ACQUIREPERM_HIT_L2_VARIANCE = 'L2_INNER_ACQUIREPERM_HIT_L2_VARIANCE'
    L2_INNER_RELEASE_HIT_L2_VARIANCE = 'L2_INNER_RELEASE_HIT_L2_VARIANCE'
    L2_INNER_RELEASEDATA_HIT_L2_VARIANCE = 'L2_INNER_RELEASEDATA_HIT_L2_VARIANCE'
    L2_OUTER_PROBE_HIT_L2_VARIANCE = 'L2_OUTER_PROBE_HIT_L2_VARIANCE'

    L2_INNER_PUTFULLDATA_HIT_L2_SHARED_VARIANCE = 'L2_INNER_PUTFULLDATA_HIT_L2_SHARED_VARIANCE'
    L2_INNER_PUTPARTIALDATA_HIT_L2_SHARED_VARIANCE = 'L2_INNER_PUTPARTIALDATA_HIT_L2_SHARED_VARIANCE'
    L2_INNER_ATOMICDATA_HIT_L2_SHARED_VARIANCE = 'L2_INNER_ATOMICDATA_HIT_L2_SHARED_VARIANCE'
    L2_INNER_GET_HIT_L2_SHARED_VARIANCE = 'L2_INNER_GET_HIT_L2_SHARED_VARIANCE'
    L2_INNER_PREFETCH_HIT_L2_SHARED_VARIANCE = 'L2_INNER_PREFETCH_HIT_L2_SHARED_VARIANCE'
    L2_INNER_ACQUIREBLOCK_HIT_L2_SHARED_VARIANCE = 'L2_INNER_ACQUIREBLOCK_HIT_L2_SHARED_VARIANCE'

    L2_INNER_ACQUIREPERM_HIT_L2_SHARED_VARIANCE = 'L2_INNER_ACQUIREPERM_HIT_L2_SHARED_VARIANCE'
    L2_OUTER_PROBE_HIT_L2_SHARED_VARIANCE = 'L2_OUTER_PROBE_HIT_L2_SHARED_VARIANCE'
    L2_OUTER_PROBE_HIT_L2_MODIFIED_VARIANCE = 'L2_OUTER_PROBE_HIT_L2_MODIFIED_VARIANCE'
    L2_OUTER_ACQUIREBLOCK_NTOB_L2_MISS_VARIANCE = 'L2_OUTER_ACQUIREBLOCK_NTOB_L2_MISS_VARIANCE'
    L2_OUTER_ACQUIREBLOCK_NTOT_L2_MISS_VARIANCE = 'L2_OUTER_ACQUIREBLOCK_NTOT_L2_MISS_VARIANCE'
    L2_OUTER_ACQUIREBLOCK_BTOT_L2_MISS_VARIANCE = 'L2_OUTER_ACQUIREBLOCK_BTOT_L2_MISS_VARIANCE'

    L2_OUTER_ACQUIREPERM_NTOT_L2_MISS_VARIANCE = 'L2_OUTER_ACQUIREPERM_NTOT_L2_MISS_VARIANCE'
    L2_OUTER_ACQUIREPERM_BTOT_L2_MISS_VARIANCE = 'L2_OUTER_ACQUIREPERM_BTOT_L2_MISS_VARIANCE'
    L2_OUTER_RELEASE_TOB_EVICTION_VARIANCE = 'L2_OUTER_RELEASE_TOB_EVICTION_VARIANCE'
    L2_OUTER_RELEASE_TON_EVICTION_VARIANCE = 'L2_OUTER_RELEASE_TON_EVICTION_VARIANCE'
    L2_OUTER_RELEASE_BTON_EVICTION_VARIANCE = 'L2_OUTER_RELEASE_BTON_EVICTION_VARIANCE'
    L2_OUTER_RELEASEDATA_TOB_VARIANCE = 'L2_OUTER_RELEASEDATA_TOB_VARIANCE'

    L2_OUTER_RELEASEDATA_TTON_DIRTY_EVICTION_VARIANCE = 'L2_OUTER_RELEASEDATA_TTON_DIRTY_EVICTION_VARIANCE'
    L2_OUTER_RELEASEDATA_BTON_VARIANCE = 'L2_OUTER_RELEASEDATA_BTON_VARIANCE'
    L2_INNER_PROBEBLOCK_TOT_CODE_MISS_VARIANCE = 'L2_INNER_PROBEBLOCK_TOT_CODE_MISS_VARIANCE'
    L2_INNER_PROBEBLOCK_TOB_LOAD_MISS_VARIANCE = 'L2_INNER_PROBEBLOCK_TOB_LOAD_MISS_VARIANCE'
    L2_INNER_PROBEBLOCK_TON_STORE_MISS_VARIANCE = 'L2_INNER_PROBEBLOCK_TON_STORE_MISS_VARIANCE'
    L2_DEMAND_MISS_HIT_MSHR_ALLOC_HINT_VARIANCE = 'L2_DEMAND_MISS_HIT_MSHR_ALLOC_HINT_VARIANCE'
    L2_CACHE_MISS_VARIANCE = 'L2_CACHE_MISS_VARIANCE'


class AuxiliaryEvents(Enum):
    NEXT_JOB_UTILIZATION = 'NEXT_JOB_UTILIZATION'


PMU_LABELS = {
    # General & Instructions
    'CPU_CYCLES': 'CPU Cycles',
    'INSTRUCTIONS_RETIRED': 'Retired Instructions',
    'EXCEPTIONS_TAKEN': 'Exceptions Taken',
    'SYSTEM_INSTRUCTIONS_RETIRED': 'System Instructions',
    # Integer
    'INTEGER_LOAD_INSTRUCTIONS_RETIRED': 'Integer Loads',
    'INTEGER_STORE_INSTRUCTIONS_RETIRED': 'Integer Stores',
    'ATOMIC_MEMORY_INSTRUCTIONS_RETIRED': 'Atomic Memory Instructions',
    'INTEGER_ARITHMETIC_INSTRUCTIONS_RETIRED': 'Integer Arithmetic',
    'INTEGER_MULTIPLICATION_INSTRUCTIONS_RETIRED': 'Integer Multiplication',
    'INTEGER_DIVISION_INSTRUCTIONS_RETIRED': 'Integer Division',
    # Floating Point
    'FLOATING_POINT_LOAD_INSTRUCTION_RETIRED': 'Floating Point Loads',
    'FLOATING_POINT_STORE_INSTRUCTION_RETIRED': 'Floating Point Stores',
    'FLOATING_POINT_ADDITION_RETIRED': 'Floating Point Addition',
    'FLOATING_POINT_MULTIPLICATION_RETIRED': 'Floating Point Multiplication',
    'FLOATING_POINT_FUSED_MULTIPLY_ADD_RETIRED': 'Floating Point Fused Multiply Add',
    'FLOATING_POINT_DIVISION_OR_SQUARE_ROOT_RETIRED': 'Floating Point Division or Square Root',
    'OTHER_FLOATING_POINT_INSTRUCTION_RETIRED': 'Other Floating Point Instructions',
    # Branches
    'CONDITIONAL_BRANCHES_RETIRED': 'Conditional Branches',
    'JAL_INSTRUCTIONS_RETIRED': 'JAL Instructions',
    'JALR_INSTRUCTIONS_RETIRED': 'JALR Instructions',
    'BRANCH_DIRECTION_MISPREDICTION': 'Branch Direction Misprediction',
    'BRANCH_JUMP_TARGET_MISPREDICTION': 'Branch Target Misprediction',
    # Interlocks & Stalls
    'ADDRESS_GENERATION_INTERLOCK': 'Address Generation Interlock',
    'LONG_LATENCY_INTERLOCK': 'Long Latency Interlock',
    'CSR_READ_INTERLOCK': 'CSR Read Interlock',
    'INTEGER_MULTIPLICATION_INTERLOCK': 'Integer Multiplication Interlock',
    'FLOATING_POINT_INTERLOCK': 'Floating Point Interlock',
    'INSTRUCTION_CACHE_ITIM_BUSY': 'Instruction Cache Busy',
    'DATA_CACHE_DTIM_BUSY': 'Data Cache Busy',
    # Pipeline Flushes
    'PIPELINE_FLUSH_FROM_CSR_WRITE': 'Pipeline Flush from CSR Write',
    'PIPELINE_FLUSH_FROM_OTHER_EVENT': 'Pipeline Flush from Other Event',
    # L1 Cache & TLB
    'INSTRUCTION_CACHE_MISS': 'Instruction Cache Miss',
    'DATA_CACHE_MISS_OR_MEMORY_MAPPED_IO_ACCESS': 'Data Cache Miss or MMIO Access',
    'DATA_CACHE_WRITE_BACK': 'Data Cache Write Back',
    'INSTRUCTION_TLB_MISS': 'Instruction TLB Miss',
    'DATA_TLB_MISS': 'Data TLB Miss',
    'L2_TLB_MISS': 'L2 TLB Miss',
}

L2_PMU_LABELS = {
    # Basic L2 Operations
    'L2_INNER_PUTFULLDATA': 'L2 Put Full Data',
    'L2_INNER_PUTPARTIALDATA': 'L2 Put Partial Data',
    'L2_INNER_ATOMICDATA': 'L2 Atomic Data',
    'L2_INNER_GET': 'L2 Get',
    'L2_INNER_PREFETCH_READ': 'L2 Prefetch Read',
    'L2_INNER_PREFETCH_WRITE': 'L2 Prefetch Write',
    # Block Acquisitions (Read/Write Intent)
    'L2_INNER_ACQUIREBLOCK_NTOB': 'L2 Acquire Block (Invalid to Shared)',
    'L2_INNER_ACQUIREBLOCK_NTOT': 'L2 Acquire Block (Invalid to Modified)',
    'L2_INNER_ACQUIREBLOCK_BTOT': 'L2 Acquire Block (Shared to Modified)',
    'L2_INNER_ACQUIREPERM_NTOT': 'L2 Acquire Permission (Invalid to Modified)',
    'L2_INNER_ACQUIREPERM_BTOT': 'L2 Acquire Permission (Shared to Modified)',
    # Evictions and Writebacks
    'L2_INNER_RELEASE_TOB': 'L2 Release (Modified to Shared)',
    'L2_INNER_RELEASE_TTON': 'L2 Release (Modified to Invalid)',
    'L2_INNER_RELEASE_BTON': 'L2 Release (Shared to Invalid)',
    'L2_INNER_RELEASEDATA_TOB': 'L2 Release Data (Modified to Shared)',
    'L2_INNER_RELEASEDATA_TTON': 'L2 Release Data (Modified to Invalid)',
    'L2_INNER_RELEASEDATA_BTON': 'L2 Release Data (Shared to Invalid)',
    # L2 Hits
    'L2_INNER_PUTFULLDATA_HIT_L2': 'L2 Put Full Data Hit',
    'L2_INNER_PUTPARTIALDATA_HIT_L2': 'L2 Put Partial Data Hit',
    'L2_INNER_ATOMICDATA_HIT_L2': 'L2 Atomic Data Hit',
    'L2_INNER_GET_HIT_L2': 'L2 Get Hit',
    'L2_INNER_PREFETCH_HIT_L2': 'L2 Prefetch Hit',
    'L2_INNER_ACQUIREBLOCK_HIT_L2': 'L2 Acquire Block Hit',
    'L2_INNER_ACQUIREPERM_HIT_L2': 'L2 Acquire Permission Hit',
    'L2_INNER_RELEASE_HIT_L2': 'L2 Release Hit',
    'L2_INNER_RELEASEDATA_HIT_L2': 'L2 Release Data Hit',
    # Hit states
    'L2_INNER_PUTFULLDATA_HIT_L2_SHARED': 'L2 Put Full Data Hit (Shared)',
    'L2_INNER_PUTPARTIALDATA_HIT_L2_SHARED': 'L2 Put Partial Data Hit (Shared)',
    'L2_INNER_ATOMICDATA_HIT_L2_SHARED': 'L2 Atomic Data Hit (Shared)',
    'L2_INNER_GET_HIT_L2_SHARED': 'L2 Get Hit (Shared)',
    'L2_INNER_PREFETCH_HIT_L2_SHARED': 'L2 Prefetch Hit (Shared)',
    'L2_INNER_ACQUIREBLOCK_HIT_L2_SHARED': 'L2 Acquire Block Hit (Shared)',
    'L2_INNER_ACQUIREPERM_HIT_L2_SHARED': 'L2 Acquire Permission Hit (Shared)',
    # L2 Misses
    'L2_OUTER_ACQUIREBLOCK_NTOB_L2_MISS': 'Outer Acquire Block Miss (Invalid to Shared)',
    'L2_OUTER_ACQUIREBLOCK_NTOT_L2_MISS': 'Outer Acquire Block Miss (Invalid to Modified)',
    'L2_OUTER_ACQUIREBLOCK_BTOT_L2_MISS': 'Outer Acquire Block Miss (Shared to Modified)',
    'L2_OUTER_ACQUIREPERM_NTOT_L2_MISS': 'Outer Acquire Permission Miss (Invalid to Modified)',
    'L2_OUTER_ACQUIREPERM_BTOT_L2_MISS': 'Outer Acquire Permission Miss (Shared to Modified)',
    # Outer / External Operations
    'L2_OUTER_PROBEBLOCK_TOT': 'Outer Probe Block (to Modified)',
    'L2_OUTER_PROBEBLOCK_TOB': 'Outer Probe Block (to Shared)',
    'L2_OUTER_PROBEBLOCK_TON': 'Outer Probe Block (to Invalid)',
    'L2_OUTER_PROBE_HIT_L2': 'Outer Probe Hit',
    'L2_OUTER_PROBE_HIT_L2_SHARED': 'Outer Probe Hit (Shared)',
    'L2_OUTER_PROBE_HIT_L2_MODIFIED': 'Outer Probe Hit (Modified)',
    'L2_OUTER_RELEASE_TOB_EVICTION': 'Outer Release Eviction (Modified to Shared)',
    'L2_OUTER_RELEASE_TON_EVICTION': 'Outer Release Eviction (Modified to Invalid)',
    'L2_OUTER_RELEASE_BTON_EVICTION': 'Outer Release Eviction (Shared to Invalid)',
    'L2_OUTER_RELEASEDATA_TOB': 'Outer Release Data (Modified to Shared)',
    'L2_OUTER_RELEASEDATA_TTON_DIRTY_EVICTION': 'Outer Release Data Dirty Eviction (Modified to Invalid)',
    'L2_OUTER_RELEASEDATA_BTON': 'Outer Release Data (Shared to Invalid)',
    # Miscellaneous
    'L2_INNER_PROBEBLOCK_TOT_CODE_MISS': 'Inner Probe Block Code Miss',
    'L2_INNER_PROBEBLOCK_TOB_LOAD_MISS': 'Inner Probe Block Load Miss',
    'L2_INNER_PROBEBLOCK_TON_STORE_MISS': 'Inner Probe Block Store Miss',
    'L2_DEMAND_MISS_HIT_MSHR_ALLOC_HINT': 'L2 Demand Miss Hit MSHR Allocation Hint',
}


class Task(Enum):
    BANDWIDTH = 'BANDWIDTH'
    DISPARITY = 'DISPARITY'
    CPU_HUNGRY = 'CPU_HUNGRY'


class TaskTiming(BaseModel):
    task: int
    address: int
    job_iterations: int = 0
    execution_time: int = 0
    job_wcet: int = 0
    iteration_wcet: int = 0
    average_job_runtime: int = 0
    average_iteration_runtime: int = 0
    iteration_per_job: int = 0


class MonitorData(BaseModel):
    event: SystemEvent | PMUEvent | L2CachePMUEvent | PMUEventVariance | L2CachePMUEventVariance
    data: list[tuple[int, int | float]]


class RunData(BaseModel):
    test_duration: int = 0
    selected_taskset: int = 0
    real_test_duration: int = 0
    task_timings: list[TaskTiming] = []
    data: dict[int, list[MonitorData]] = {}


class TaskData(BaseModel):
    task: Task
    address: int
    core: str
    data: list[MonitorData]


class TaskDataset(BaseModel):
    data: list[TaskData]


class ParsingState(Enum):
    RUN_INFO = 0
    MONITOR_INFO = 1
    TASK_TIMINGS = 2
    DATA = 3
    END = 4


class TaskRateParsingState(Enum):
    RUN_INFO = 0
    DATA = 1
    END = 2


class DataOrigin(Enum):
    GLOBAL = 'GLOBAL'
    CORE_1 = 'CORE_1'
    CORE_2 = 'CORE_2'
    CORE_3 = 'CORE_3'


class Dataset(BaseModel):
    data: dict[DataOrigin, list[MonitorData]]


class TaskRateDataset(BaseModel):
    taskset: int
    data: dict[int, list[MonitorData]]


class TaskInfo(BaseModel):
    task: Task
    period: int


class Taskset(BaseModel):
    tasks: tuple[TaskInfo, ...]
    origin_map: dict[DataOrigin, tuple[TaskInfo, ...]]
    hyperperiod: int
    assigned_core_map: tuple[DataOrigin, ...]


TASKSET_1_TASKS = (
    TaskInfo(**{'task': Task.BANDWIDTH, 'period': 1000000}),
    TaskInfo(**{'task': Task.DISPARITY, 'period': 1000000}),
    TaskInfo(**{'task': Task.DISPARITY, 'period': 1000000}),
    TaskInfo(**{'task': Task.CPU_HUNGRY, 'period': 1000000}),
    TaskInfo(**{'task': Task.CPU_HUNGRY, 'period': 1000000}),
    TaskInfo(**{'task': Task.DISPARITY, 'period': 1000000}),
)

TASKSET_1_ORIGIN_MAP = {
    DataOrigin.CORE_1: (TASKSET_1_TASKS[0], TASKSET_1_TASKS[1]),
    DataOrigin.CORE_2: (TASKSET_1_TASKS[2], TASKSET_1_TASKS[3]),
    DataOrigin.CORE_3: (TASKSET_1_TASKS[4], TASKSET_1_TASKS[5]),
}

TASKSET_1_ASSIGNED_CORE_MAP = (
    DataOrigin.CORE_1,
    DataOrigin.CORE_1,
    DataOrigin.CORE_2,
    DataOrigin.CORE_2,
    DataOrigin.CORE_3,
    DataOrigin.CORE_3,
)

TASKSET_2_TASKS = (
    TaskInfo(**{'task': Task.BANDWIDTH, 'period': 500000}),
    TaskInfo(**{'task': Task.DISPARITY, 'period': 1000000}),
    TaskInfo(**{'task': Task.DISPARITY, 'period': 2000000}),
    TaskInfo(**{'task': Task.CPU_HUNGRY, 'period': 500000}),
    TaskInfo(**{'task': Task.CPU_HUNGRY, 'period': 250000}),
    TaskInfo(**{'task': Task.DISPARITY, 'period': 500000}),
)

TASKSET_2_ORIGIN_MAP = {
    DataOrigin.CORE_1: (TASKSET_2_TASKS[0], TASKSET_2_TASKS[1]),
    DataOrigin.CORE_2: (TASKSET_2_TASKS[2], TASKSET_2_TASKS[3]),
    DataOrigin.CORE_3: (TASKSET_2_TASKS[4], TASKSET_2_TASKS[5]),
}

TASKSET_2_ASSIGNED_CORE_MAP = (
    DataOrigin.CORE_1,
    DataOrigin.CORE_1,
    DataOrigin.CORE_2,
    DataOrigin.CORE_2,
    DataOrigin.CORE_3,
    DataOrigin.CORE_3,
)

TASKSET_3_TASKS = (
    TaskInfo(**{'task': Task.BANDWIDTH, 'period': 200000}),
    TaskInfo(**{'task': Task.BANDWIDTH, 'period': 200000}),
    TaskInfo(**{'task': Task.DISPARITY, 'period': 2000000}),
    TaskInfo(**{'task': Task.CPU_HUNGRY, 'period': 200000}),
    TaskInfo(**{'task': Task.DISPARITY, 'period': 1000000}),
    TaskInfo(**{'task': Task.CPU_HUNGRY, 'period': 500000}),
    TaskInfo(**{'task': Task.BANDWIDTH, 'period': 2000000}),
)

TASKSET_3_ORIGIN_MAP = {
    DataOrigin.CORE_1: (TASKSET_3_TASKS[0],),
    DataOrigin.CORE_2: (TASKSET_3_TASKS[1], TASKSET_3_TASKS[2]),
    DataOrigin.CORE_3: (TASKSET_3_TASKS[3], TASKSET_3_TASKS[4], TASKSET_3_TASKS[5], TASKSET_3_TASKS[6]),
}

TASKSET_3_ASSIGNED_CORE_MAP = (
    DataOrigin.CORE_1,
    DataOrigin.CORE_2,
    DataOrigin.CORE_2,
    DataOrigin.CORE_3,
    DataOrigin.CORE_3,
    DataOrigin.CORE_3,
    DataOrigin.CORE_3,
)

TASKSET_5_TASKS = (
    TaskInfo(**{'task': Task.BANDWIDTH, 'period': 1000000}),
    TaskInfo(**{'task': Task.DISPARITY, 'period': 1000000}),
    TaskInfo(**{'task': Task.DISPARITY, 'period': 1000000}),
    TaskInfo(**{'task': Task.CPU_HUNGRY, 'period': 1000000}),
    TaskInfo(**{'task': Task.CPU_HUNGRY, 'period': 1000000}),
    TaskInfo(**{'task': Task.DISPARITY, 'period': 1000000}),
)

TASKSET_5_ORIGIN_MAP = {
    DataOrigin.CORE_1: (TASKSET_1_TASKS[0], TASKSET_1_TASKS[1]),
    DataOrigin.CORE_2: (TASKSET_1_TASKS[2], TASKSET_1_TASKS[3]),
    DataOrigin.CORE_3: (TASKSET_1_TASKS[4], TASKSET_1_TASKS[5]),
}

TASKSET_5_ASSIGNED_CORE_MAP = (
    DataOrigin.CORE_1,
    DataOrigin.CORE_1,
    DataOrigin.CORE_2,
    DataOrigin.CORE_2,
    DataOrigin.CORE_3,
    DataOrigin.CORE_3,
)

TASKSET_6_TASKS = (
    TaskInfo(**{'task': Task.BANDWIDTH, 'period': 500000}),
    TaskInfo(**{'task': Task.DISPARITY, 'period': 1000000}),
    TaskInfo(**{'task': Task.DISPARITY, 'period': 2000000}),
    TaskInfo(**{'task': Task.CPU_HUNGRY, 'period': 500000}),
    TaskInfo(**{'task': Task.CPU_HUNGRY, 'period': 250000}),
    TaskInfo(**{'task': Task.DISPARITY, 'period': 500000}),
)

TASKSET_6_ORIGIN_MAP = {
    DataOrigin.CORE_1: (TASKSET_6_TASKS[0], TASKSET_6_TASKS[1]),
    DataOrigin.CORE_2: (TASKSET_6_TASKS[2], TASKSET_6_TASKS[3]),
    DataOrigin.CORE_3: (TASKSET_6_TASKS[4], TASKSET_6_TASKS[5]),
}

TASKSET_6_ASSIGNED_CORE_MAP = (
    DataOrigin.CORE_1,
    DataOrigin.CORE_1,
    DataOrigin.CORE_2,
    DataOrigin.CORE_2,
    DataOrigin.CORE_3,
    DataOrigin.CORE_3,
)

TASKSET_1 = Taskset(
    **{
        'tasks': TASKSET_1_TASKS,
        'origin_map': TASKSET_1_ORIGIN_MAP,
        'hyperperiod': 1000000,
        'assigned_core_map': TASKSET_1_ASSIGNED_CORE_MAP,
    }
)

TASKSET_2 = Taskset(
    **{
        'tasks': TASKSET_2_TASKS,
        'origin_map': TASKSET_2_ORIGIN_MAP,
        'hyperperiod': 2000000,
        'assigned_core_map': TASKSET_2_ASSIGNED_CORE_MAP,
    }
)

TASKSET_3 = Taskset(
    **{
        'tasks': TASKSET_3_TASKS,
        'origin_map': TASKSET_3_ORIGIN_MAP,
        'hyperperiod': 2000000,
        'assigned_core_map': TASKSET_3_ASSIGNED_CORE_MAP,
    }
)

TASKSET_5 = Taskset(
    **{
        'tasks': TASKSET_5_TASKS,
        'origin_map': TASKSET_5_ORIGIN_MAP,
        'hyperperiod': 2000000,
        'assigned_core_map': TASKSET_5_ASSIGNED_CORE_MAP,
    }
)

TASKSET_6 = Taskset(
    **{
        'tasks': TASKSET_6_TASKS,
        'origin_map': TASKSET_6_ORIGIN_MAP,
        'hyperperiod': 2000000,
        'assigned_core_map': TASKSET_5_ASSIGNED_CORE_MAP,
    }
)

TASKSETS = {1: TASKSET_1, 2: TASKSET_2, 3: TASKSET_3, 5: TASKSET_5, 6: TASKSET_6}

# WCET for the taskset 1
WCET = 200000  # us
