// EPOS RISC-V 64 PMU Mediator

#include <architecture/rv64/rv64_pmu.h>

__BEGIN_SYS

const RV32_PMU::Event RV32_PMU::_events[EVENTS] = {
    CYCLES,  // CPU_CYCLES
    TIME,    // UNHALTED_CYCLES

    INSTRUCTIONS_RETIRED,                         // INSTRUCTIONS_RETIRED
    INTEGER_LOAD_INSTRUCTIONS_RETIRED,            // LOAD_INSTRUCTIONS_RETIRED
    INTEGER_STORE_INSTRUCTIONS_RETIRED,           // STORE_INSTRUCTIONS_RETIRED
    INTEGER_ARITHMETIC_INSTRUCTIONS_RETIRED,      // INTEGER_ARITHMETIC_INSTRUCTIONS_RETIRED
    INTEGER_MULTIPLICATION_INSTRUCTIONS_RETIRED,  // INTEGER_MULTIPLICATION_INSTRUCTIONS_RETIRED
    INTEGER_DIVISION_INSTRUCTIONS_RETIRED,        // INTEGER_DIVISION_INSTRUCTIONS_RETIRED
    UNSUPORTED_EVENT,                             // FPU_INSTRUCTIONS_RETIRED
    UNSUPORTED_EVENT,                             // SIMD_INSTRUCTIONS_RETIRED
    ATOMIC_MEMORY_INSTRUCTIONS_RETIRED,           // ATOMIC_MEMORY_INSTRUCTIONS_RETIRED

    UNSUPORTED_EVENT,                  // BRANCHES
    UNSUPORTED_EVENT,                  // IMIDIATE_BRANCHES
    CONDITIONAL_BRANCHES_RETIRED,      // CONDITIONAL_BRANCHES
    BRANCH_JUMP_TARGET_MISPREDICTION,  // BRANCH_MISPREDICTIONS
    BRANCH_DIRECTION_MISPREDICTION,    // BRANCH_DIRECTION_MISPREDICTIONS
    UNSUPORTED_EVENT,                  // CONDITIONAL_BRANCH_MISPREDICTIONS

    EXCEPTIONS_TAKEN,  // EXCEPTIONS
    UNSUPORTED_EVENT,  // INTERRUPTS

    UNSUPORTED_EVENT,        // L1_CACHE_HITS
    L1_CACHE_MISS,           // L1_CACHE_MISSES
    UNSUPORTED_EVENT,        // L1_DATA_CACHE_MISSES
    DATA_CACHE_WRITE_BACK,   // L1_DATA_CACHE_WRITEBACKS
    INSTRUCTION_CACHE_MISS,  // L1_INSTRUCTION_CACHE_MISSES
    UNSUPORTED_EVENT,        // L2_CACHE_HITS
    UNSUPORTED_EVENT,        // L2_CACHE_MISSES
    UNSUPORTED_EVENT,        // L2_DATA_CACHE_MISSES
    UNSUPORTED_EVENT,        // L2_DATA_CACHE_WRITEBACKS
    UNSUPORTED_EVENT,        // L3_CACHE_HITS
    UNSUPORTED_EVENT,        // L3_CACHE_MISSES
    UNSUPORTED_EVENT,        // INSTRUCTION_MEMORY_ACCESSES
    UNSUPORTED_EVENT,        // UNCACHED_MEMORY_ACCESSES
    UNSUPORTED_EVENT,        // UNALIGNED_MEMORY_ACCESSES

    UNSUPORTED_EVENT,  // BUS_CYCLES
    UNSUPORTED_EVENT,  // BUS_ACCESSES
    UNSUPORTED_EVENT,  // TLB_MISSES
    UNSUPORTED_EVENT,  // INSTRUCTION_TLB_MISSES
    UNSUPORTED_EVENT,  // MEMORY_ERRORS

    UNSUPORTED_EVENT,  // STALL_CYCLES
    UNSUPORTED_EVENT,  // STALL_CYCLES_CACHE
    UNSUPORTED_EVENT,  // STALL_CYCLES_DATA_CACHE
    UNSUPORTED_EVENT,  // STALL_CYCLES_TLB
    UNSUPORTED_EVENT,  // STALL_CYCLES_MEMORY
    UNSUPORTED_EVENT,  // PIPELINE_SERIALIZATIONS
    UNSUPORTED_EVENT,  // BUS_SERIALIZATION

    SYSTEM_INSTRUCTIONS_RETIRED,                 // ARCHITECTURE_DEPENDENT_EVENT45
    JAL_INSTRUCTIONS_RETIRED,                    // ARCHITECTURE_DEPENDENT_EVENT46
    JALR_INSTRUCTIONS_RETIRED,                   // ARCHITECTURE_DEPENDENT_EVENT47
    ADDRESS_GENERATION_INTERLOCK,                // ARCHITECTURE_DEPENDENT_EVENT48
    LONG_LATENCY_INTERLOCK,                      // ARCHITECTURE_DEPENDENT_EVENT49
    CSR_READ_INTERLOCK,                          // ARCHITECTURE_DEPENDENT_EVENT50
    INSTRUCTION_CACHE_ITIM_BUSY,                 // ARCHITECTURE_DEPENDENT_EVENT51
    DATA_CACHE_DTIM_BUSY,                        // ARCHITECTURE_DEPENDENT_EVENT52
    PIPELINE_FLUSH_FROM_CSR_WRITE,               // ARCHITECTURE_DEPENDENT_EVENT53
    PIPELINE_FLUSH_FROM_OTHER_EVENT,             // ARCHITECTURE_DEPENDENT_EVENT54
    INTEGER_MULTIPLICATION_INTERLOCK,            // ARCHITECTURE_DEPENDENT_EVENT55
    FLOATING_POINT_LOAD_INSTRUCTION_RETIRED,     // ARCHITECTURE_DEPENDENT_EVENT56
    FLOATING_POINT_STORE_INSTRUCTION_RETIRED,    // ARCHITECTURE_DEPENDENT_EVENT57
    FLOATING_POINT_FUSED_MULTIPLY_ADD_RETIRED,   // ARCHITECTURE_DEPENDENT_EVENT58
    FLOATING_POINT_INTERLOCK,                    // ARCHITECTURE_DEPENDENT_EVENT59
    DATA_CACHE_MISS_OR_MEMORY_MAPPED_IO_ACCESS,  // ARCHITECTURE_DEPENDENT_EVENT60
};

const RV64_PMU::Event RV64_PMU::_l2pm_events[EVENTS] = {
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT61
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT62
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT63
    L2_INNER_GET,                              // ARCHITECTURE_DEPENDENT_EVENT64
    L2_INNER_PREFETCH_READ,                    // ARCHITECTURE_DEPENDENT_EVENT65
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT66
    L2_INNER_ACQUIREBLOCK_NTOB,                // ARCHITECTURE_DEPENDENT_EVENT67
    L2_INNER_ACQUIREBLOCK_NTOT,                // ARCHITECTURE_DEPENDENT_EVENT68
    L2_INNER_ACQUIREBLOCK_BTOT,                // ARCHITECTURE_DEPENDENT_EVENT69
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT70
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT71
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT72
    L2_INNER_RELEASE_TTON,                     // ARCHITECTURE_DEPENDENT_EVENT73
    L2_INNER_RELEASE_BTON,                     // ARCHITECTURE_DEPENDENT_EVENT74
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT75
    L2_INNER_RELEASEDATA_TTON,                 // ARCHITECTURE_DEPENDENT_EVENT76
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT77
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT78
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT79
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT80
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT81
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT82
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT83
    L2_INNER_GET_HIT_L2,                       // ARCHITECTURE_DEPENDENT_EVENT84
    L2_INNER_PREFETCH_HIT_L2,                  // ARCHITECTURE_DEPENDENT_EVENT85
    L2_INNER_ACQUIREBLOCK_HIT_L2,              // ARCHITECTURE_DEPENDENT_EVENT86
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT87
    L2_INNER_RELEASE_HIT_L2,                   // ARCHITECTURE_DEPENDENT_EVENT88
    L2_INNER_RELEASEDATA_HIT_L2,               // ARCHITECTURE_DEPENDENT_EVENT89
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT90
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT91
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT92
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT93
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT94
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT95
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT96
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT97
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT98
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT99
    L2_OUTER_ACQUIREBLOCK_NTOB_L2_MISS,        // ARCHITECTURE_DEPENDENT_EVENT100
    L2_OUTER_ACQUIREBLOCK_NTOT_L2_MISS,        // ARCHITECTURE_DEPENDENT_EVENT101
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT102
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT103
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT104
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT105
    L2_OUTER_RELEASE_TON_EVICTION,             // ARCHITECTURE_DEPENDENT_EVENT106
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT107
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT108
    L2_OUTER_RELEASEDATA_TTON_DIRTY_EVICTION,  // ARCHITECTURE_DEPENDENT_EVENT109
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT110
    UNSUPORTED_EVENT,                          // ARCHITECTURE_DEPENDENT_EVENT111
    L2_INNER_PROBEBLOCK_TOB_LOAD_MISS,         // ARCHITECTURE_DEPENDENT_EVENT112
    L2_INNER_PROBEBLOCK_TON_STORE_MISS,        // ARCHITECTURE_DEPENDENT_EVENT113
    L2_DEMAND_MISS_HIT_MSHR_ALLOC_HINT,        // ARCHITECTURE_DEPENDENT_EVENT114
    L2_CACHE_MISS,                             // ARCHITECTURE_DEPENDENT_EVENT115
    L1_BY_L2                                   // ARCHITECTURE_DEPENDENT_EVENT116
};

__END_SYS
